name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: CI
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: make init-ci
      - name: Test with unittest
        run: make test
      - name: Build docker image
        run: make build
